@enum EXOS_ERROR_CODE begin
    EXOS_ERROR_OK = 0
    EXOS_ERROR_NOT_IMPLEMENTED = 5000
    EXOS_ERROR_PARAMETER_NULL
    EXOS_ERROR_BAD_DATAMODEL_HANDLE
    EXOS_ERROR_BAD_DATASET_HANDLE
    EXOS_ERROR_BAD_LOG_HANDLE
    EXOS_ERROR_BAD_SYNC_HANDLE
    EXOS_ERROR_NOT_ALLOWED
    EXOS_ERROR_NOT_FOUND
    EXOS_ERROR_STRING_FORMAT
    EXOS_ERROR_MESSAGE_FORMAT
    EXOS_ERROR_NO_DATA
    EXOS_ERROR_BUFFER_OVERFLOW
    EXOS_ERROR_TIMEOUT
    EXOS_ERROR_BAD_DATASET_SIZE
    EXOS_ERROR_USER
    EXOS_ERROR_SYSTEM
    EXOS_ERROR_SYSTEM_SOCKET
    EXOS_ERROR_SYSTEM_SOCKET_USAGE
    EXOS_ERROR_SYSTEM_MALLOC
    EXOS_ERROR_SYSTEM_LXI
    EXOS_ERROR_DMR_NOT_READY
    EXOS_ERROR_DMR_SHUTDOWN
    EXOS_ERROR_BAD_STATE
end

@enum EXOS_CONNECTION_STATE begin
    EXOS_STATE_DISCONNECTED
    EXOS_STATE_CONNECTED
    EXOS_STATE_OPERATIONAL
    EXOS_STATE_ABORTED
end

@enum EXOS_DATAMODEL_EVENT_TYPE begin
    EXOS_DATAMODEL_EVENT_CONNECTION_CHANGED
    EXOS_DATAMODEL_EVENT_SYNC_STATE_CHANGED
end

@enum EXOS_DATAMODEL_PROCESS_MODE begin
    EXOS_DATAMODEL_PROCESS_BLOCKING
    EXOS_DATAMODEL_PROCESS_NON_BLOCKING
end

@enum EXOS_DATASET_TYPE begin
    EXOS_DATASET_SUBSCRIBE = 1
    EXOS_DATASET_PUBLISH = 16
end

@enum EXOS_DATASET_EVENT_TYPE begin
    EXOS_DATASET_EVENT_CONNECTION_CHANGED
    EXOS_DATASET_EVENT_UPDATED
    EXOS_DATASET_EVENT_PUBLISHED
    EXOS_DATASET_EVENT_DELIVERED
end

@enum EXOS_LOG_LEVEL begin
    EXOS_LOG_LEVEL_ERROR
    EXOS_LOG_LEVEL_WARNING
    EXOS_LOG_LEVEL_SUCCESS
    EXOS_LOG_LEVEL_INFO
    EXOS_LOG_LEVEL_DEBUG
end

@enum EXOS_LOG_TYPE begin
    EXOS_LOG_TYPE_ALWAYS  = 0
    EXOS_LOG_TYPE_USER    = 1
    EXOS_LOG_TYPE_SYSTEM  = 2
    EXOS_LOG_TYPE_VERBOSE = 4
end
